data <- read.csv("./trimmed_household_consumption.txt", sep=";")
days <- strptime(paste(data$Date, data$Time), format="%d/%m/%Y %H:%M:%S")
par(mfrow = c(2, 2), mar=c(4,4,0.5,5))
plot(days, data$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(days, data$Voltage, type="l", xlab="", ylab="Voltage")
plot(days, data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(days, data$Sub_metering_2, col="red")
lines(days, data$Sub_metering_3, col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = "solid", bty = "n")
plot(days, data$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
png("plot4.png")
